<style>
    .privacy-policy{
        width: 100%;
        height: auto;
        padding-top: 5rem;
        padding-bottom: 5rem;
        background-color: whitesmoke;
    }
    .privacy-policy .box{
        border: 1px solid #cdcdcd;
        background-color: white;
        padding: 5rem 2rem;
    }
    .privacy-policy h1{
        text-align: center;
        text-transform: uppercase;
        text-decoration:underline;
        color: #212529;
        font-family: sohne,"Helvetica Neue",Helvetica,Arial,sans-serif !important;
        font-size: 30px;
        font-weight: 500 !important;
        margin-bottom: 4rem;
    }
    .privacy-policy p{
        color: rgb( 95, 96, 96 );
        font-size: 17px;
        font-family:  sohne,"Helvetica Neue",Helvetica,Arial,sans-serif !important;
        font-weight: 300 !important;
        
        line-height: 1.7;
    }
    .privacy-policy h3{
        text-decoration:underline;
        color: #212529 !important;
        font-family: sohne,"Helvetica Neue",Helvetica,Arial,sans-serif !important;
        margin-top: 3rem;
    }
    .privacy-policy li{
        color: rgb( 95, 96, 96 );
        font-size: 17px;
        font-family:  sohne,"Helvetica Neue",Helvetica,Arial,sans-serif !important;
      
        
        line-height: 1.7;
        margin-bottom: 1rem;
    }

    @media only screen and (max-width: 600px) {
        .privacy-policy li{
            font-size: 15px;
        }
        .privacy-policy p{
            font-size: 15px;
        }
}
</style>
<div class="privacy-policy">
    <div class="container box">
      
            <h1>Privacy Policy</h1>
            <p>Dogbazar.org  will only disclose your Personal Information in accordance with this Privacy Policy. If you decline to submit personal information to us, then we will unfortunately not be in a position to provide the Services to you.</p>
            
            <p>Any of your personal information which you provide when you use Dogbazar.org in an unencrypted manner and/or to an open, public environment or forum including (without limitation) any blog, chat room, albums, community, classifieds or discussion board, is not confidential, does not constitute Personal Information, and is not subject to protection under Privacy Policy.</p>
            <p>Since such public environments are accessible by third parties, it is possible that third parties may collect and collate and use such information for their own purposes. You should accordingly be careful when deciding to share any of your Personal Information in such public environments.</p>
            <p>accordingly be careful when deciding to share any of your Personal Information in such public environments. Dogbazar is not liable to you or any third party for any damages that you or any third party may suffer howsoever arising from your disclosure of Personal Information in any public environment. Disclose your personal information in a public environment at your own risk.</p>
            <h3>The Information Dogbazar may collect:</h3>
            <ol>
                <li><b>User-provided Information:</b> When you register for, browse and use the Website, you may provide to Dogbazar “identity information” (such as your name, email address, address, home or mobile telephone number etc.). You may also be able to add a picture of yourself.</li>
                <li>If you decide to register through or otherwise grant access to a third party, social networking or authentication service that we may make available (“Authentication Service“), such as Facebook Connect or Google, Dogbazar may also collect any such “identity information” that you have provided to the Authentication Service from the account you have with the Authentication Service.</li>
                <li>Details of transactions by your Facebook friends and other Facebook users generated by you through our Service.</li>
                <li>If you choose to provide such information, during registration or otherwise, you are giving Dogbazar the permission to use and store it consistent with this policy. Therefore, please understand that when you sign in with Dogbazar, you are not anonymous to us.</li>
               
            </ol>
            <h3>IP Addresses and cookies</h3>
            <p>We may collect information about your computer, including where available your IP address, operating system and browser type, for system administration and to report aggregate information to our advertisers. We may also collect such information from your Facebook friends and other Facebook users who use the Service. This is statistical data about our users’ browsing actions and patterns, and does not identify any individual.</p>
            <ul>
                <li>Please note that our advertisers may also use cookies, over which we have no control.</li>
            </ul>
            <h3>The Way Dogbazar Uses Information</h3>
            <p>Dogbazar uses the information that you provide or that we collect in order to establish and enhance our relationship with you. Dogbazar generally uses the information you provide or that we collect to operate, maintain, enhance, and provide all of the features and services found on the Website. If you have given Dogbazar consent, we may use your personally identifiable information to provide you with information about Dogbazar’s features, services and other offerings that may be of interest to you. We may also send information or offers to groups of users on behalf of other businesses.</p>
            <h3>When Dogbazar Discloses Information</h3>
            <ol>
                <li><b>Social Networks:</b> Dogbazar will disclose your personal information if you have explicitly agreed that we may do so. In particular, we will disclose personal information where you have elected to connect your account on our Website to a social network or other similar service (e.g., Facebook or Google), or have elected to have your activity on our Website published to a social network or other similar service (e.g., Facebook or Google). To control the information that you share, you should review and, if appropriate, modify your privacy settings on such services.</li>
                <li><b>Required by Law:</b> Dogbazar may also disclose user information if required to do so by law or in the good-faith belief that such action is necessary to comply with state and other governing bodies</li>
                <li><b>Merger or Acquisition:</b> In the event that Dogbazar is acquired by or merged with a third-party entity, we reserve the right, in any of these circumstances, to transfer or assign the information that we have collected from users as part of such merger, acquisition, sale, or other change of control.</li>
                <li><b>Other Purposes:</b> Dogbazar also reserves the right to disclose user information that we believe, in good faith, is appropriate or necessary to take precautions against liability; protect Dogbazar from fraudulent, abusive, or unlawful uses; to investigate and defend ourselves against any third-party claims or allegations; to assist government enforcement agencies; to protect the security or integrity of the Website; or to protect the rights, property, or personal safety of Dogbazar, our Users, or others.</li>
            </ol>
        
    </div>
</div>